# Generated by Django 3.1.2 on 2020-11-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department'),
        ('companies', '0001_initial'),
        ('employees', '0005_auto_20201105_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departament',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
