# Generated by Django 3.1.2 on 2020-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201028_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
