# Generated by Django 3.1.2 on 2020-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department'),
        ('employees', '0004_auto_20201029_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departaments',
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(to='departments.Department'),
        ),
    ]
